-- GENERATED by tools/emit_gold_reference_views.py. Do not edit.
--
-- Currently-offered Workday reference values. A reference appears here while its most
-- recent effectivity row says OFFERED; a WITHDRAWN row removes it without deleting any
-- history, because the satellite is insert-only.
CREATE OR REPLACE VIEW `${gold_catalog}`.`reference_data`.`wd_reference` AS
SELECT
  h.reference_id_type,
  h.reference_id,
  e.reference_status,
  e.applied_dts AS effective_from
FROM `${catalog}`.`raw_vault`.`hub_wd_reference` h
JOIN (
  SELECT
    wd_reference_hk,
    reference_status,
    applied_dts,
    ROW_NUMBER() OVER (PARTITION BY wd_reference_hk
                       ORDER BY applied_dts DESC, load_dts DESC) AS rn
  FROM `${catalog}`.`raw_vault`.`esat_wd_reference_effectivity_workday`
) e
  ON e.wd_reference_hk = h.wd_reference_hk AND e.rn = 1
WHERE e.reference_status = 'OFFERED';
