-- GENERATED by tools/emit_gold_schemas.py from accelerator.gold_layout.SCHEMAS.
-- Do not edit. Run the emitter and commit the result.
--
-- Applied by checks/apply_gold_schemas.py, from the gold_build job.
-- CREATE ... IF NOT EXISTS only: a schema is a securable, and replacing one
-- discards every grant held against it (DEF-61).

-- reference_data: shared conformed reference -- calendars, code lists, currency
CREATE SCHEMA IF NOT EXISTS `${gold_catalog}`.`reference_data`;

-- master_data: shared conformed master entities -- legal entity, worker, supplier
CREATE SCHEMA IF NOT EXISTS `${gold_catalog}`.`master_data`;

-- wd_fin_export: the project schema -- Workday finance export tables
CREATE SCHEMA IF NOT EXISTS `${gold_catalog}`.`wd_fin_export`;

-- governance: gold's mask functions and grant DDL
CREATE SCHEMA IF NOT EXISTS `${gold_catalog}`.`governance`;

-- control: aud_load_run, aud_table_load, aud_table_discard
CREATE SCHEMA IF NOT EXISTS `${gold_catalog}`.`control`;
