-- GENERATED by tools/emit_uc_constraints.py -- do not hand-edit.
-- verify_repo.py fails the build if this file and the model disagree.
--
-- The vault's relationship model, as Unity Catalog informational constraints. Derived from
-- metadata/entities/ through contract.grain (primary keys, mirroring append_only_check's
-- uniqueness rule) and contract.foreign_keys (edges, the same function the DBML diagram and
-- the OWL ontology read).
--
-- INFORMATIONAL, NEVER ENFORCED. Unity Catalog does not enforce these and enforcement would
-- be wrong here: a satellite legitimately arrives before its hub within a run. What they buy
-- is a join path a query planner, a BI tool or an agent can discover instead of guess.
--
-- NOTHING RUNS THIS YET. Two questions need a workspace, not an opinion:
--   1. does an SDP streaming table accept ALTER TABLE ... ADD CONSTRAINT?
--   2. is every key column already NOT NULL, which UC requires of a primary key?
-- Until both are answered this file is generated, committed and gated -- the same state
-- governance/control_objects_gold.sql has been in since 29 August.
--
-- ${catalog} and ${vault_schema} / ${business_vault_schema} are substituted by the caller.
--
-- 49 primary key(s), 56 foreign key(s), 105 statement(s).

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_accounting_journal_rev1`
  ADD CONSTRAINT `hub_accounting_journal_rev1_pk` PRIMARY KEY (`accounting_journal_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_accounting_journal_header_ukg_us_rev1`
  ADD CONSTRAINT `sat_accounting_journal_header_ukg_us_rev1_pk` PRIMARY KEY (`accounting_journal_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_accounting_journal_header_ukg_us_rev1`
  ADD CONSTRAINT `sat_accounting_journal_header_ukg_us_rev1_accounting_journal_hk_fk` FOREIGN KEY (`accounting_journal_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_accounting_journal_rev1` (`accounting_journal_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_client_rev1`
  ADD CONSTRAINT `hub_client_rev1_pk` PRIMARY KEY (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_client_address_gp_customer_rev1`
  ADD CONSTRAINT `msat_client_address_gp_customer_rev1_pk` PRIMARY KEY (`client_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_client_address_gp_customer_rev1`
  ADD CONSTRAINT `msat_client_address_gp_customer_rev1_client_hk_fk` FOREIGN KEY (`client_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_client_rev1` (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_contracting_entity_rev2`
  ADD CONSTRAINT `lnk_client_contracting_entity_rev2_pk` PRIMARY KEY (`client_contracting_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_contracting_entity_rev2`
  ADD CONSTRAINT `lnk_client_contracting_entity_rev2_contracting_legal_entity_hk_fk` FOREIGN KEY (`contracting_legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_contracting_entity_rev2`
  ADD CONSTRAINT `lnk_client_contracting_entity_rev2_engaging_legal_entity_hk_fk` FOREIGN KEY (`engaging_legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_client_contracting_entity_effectivity_client_portal_rev1`
  ADD CONSTRAINT `esat_client_contracting_entity_effectivity_client_portal_rev1_pk` PRIMARY KEY (`client_contracting_entity_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_client_contracting_entity_effectivity_client_portal_rev1`
  ADD CONSTRAINT `esat_client_contracting_entity_effectivity_client_portal_rev1_client_contracting_entity_hk_fk` FOREIGN KEY (`client_contracting_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`lnk_client_contracting_entity_rev2` (`client_contracting_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_client_details_gp_customer_rev1`
  ADD CONSTRAINT `sat_client_details_gp_customer_rev1_pk` PRIMARY KEY (`client_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_client_details_gp_customer_rev1`
  ADD CONSTRAINT `sat_client_details_gp_customer_rev1_client_hk_fk` FOREIGN KEY (`client_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_client_rev1` (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_job_request_rev2`
  ADD CONSTRAINT `lnk_client_job_request_rev2_pk` PRIMARY KEY (`client_job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_job_request_rev2`
  ADD CONSTRAINT `lnk_client_job_request_rev2_client_hk_fk` FOREIGN KEY (`client_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_client_rev1` (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_client_job_request_rev2`
  ADD CONSTRAINT `lnk_client_job_request_rev2_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_client_legal_entity_hierarchy_rev2`
  ADD CONSTRAINT `hal_client_legal_entity_hierarchy_rev2_pk` PRIMARY KEY (`client_legal_entity_hierarchy_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_client_legal_entity_hierarchy_rev2`
  ADD CONSTRAINT `hal_client_legal_entity_hierarchy_rev2_child_legal_entity_hk_fk` FOREIGN KEY (`child_legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_client_legal_entity_hierarchy_rev2`
  ADD CONSTRAINT `hal_client_legal_entity_hierarchy_rev2_parent_legal_entity_hk_fk` FOREIGN KEY (`parent_legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_client_legal_entity_hierarchy_effectivity_hubspot_rev1`
  ADD CONSTRAINT `esat_client_legal_entity_hierarchy_effectivity_hubspot_rev1_pk` PRIMARY KEY (`client_legal_entity_hierarchy_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_client_legal_entity_hierarchy_effectivity_hubspot_rev1`
  ADD CONSTRAINT `esat_client_legal_entity_hierarchy_effectivity_hubspot_rev1_client_legal_entity_hierarchy_hk_fk` FOREIGN KEY (`client_legal_entity_hierarchy_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hal_client_legal_entity_hierarchy_rev2` (`client_legal_entity_hierarchy_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_consolidation_group_rev1`
  ADD CONSTRAINT `hub_consolidation_group_rev1_pk` PRIMARY KEY (`consolidation_group_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_consolidation_hierarchy_rev2`
  ADD CONSTRAINT `hal_consolidation_hierarchy_rev2_pk` PRIMARY KEY (`consolidation_hierarchy_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_consolidation_hierarchy_rev2`
  ADD CONSTRAINT `hal_consolidation_hierarchy_rev2_child_consolidation_group_hk_fk` FOREIGN KEY (`child_consolidation_group_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_consolidation_group_rev1` (`consolidation_group_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hal_consolidation_hierarchy_rev2`
  ADD CONSTRAINT `hal_consolidation_hierarchy_rev2_parent_consolidation_group_hk_fk` FOREIGN KEY (`parent_consolidation_group_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_consolidation_group_rev1` (`consolidation_group_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_consolidation_hierarchy_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_consolidation_hierarchy_effectivity_workday_rev1_pk` PRIMARY KEY (`consolidation_hierarchy_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_consolidation_hierarchy_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_consolidation_hierarchy_effectivity_workday_rev1_consolidation_hierarchy_hk_fk` FOREIGN KEY (`consolidation_hierarchy_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hal_consolidation_hierarchy_rev2` (`consolidation_hierarchy_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_rev2_pk` PRIMARY KEY (`general_journal_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_rev2_accounting_journal_hk_fk` FOREIGN KEY (`accounting_journal_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_accounting_journal_rev1` (`accounting_journal_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_rev2_ledger_account_hk_fk` FOREIGN KEY (`ledger_account_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_ledger_account_rev1` (`ledger_account_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_rev2_operating_company_hk_fk` FOREIGN KEY (`operating_company_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_operating_company_rev1` (`operating_company_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_closed_year_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_closed_year_rev2_pk` PRIMARY KEY (`general_journal_line_closed_year_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_closed_year_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_closed_year_rev2_accounting_journal_hk_fk` FOREIGN KEY (`accounting_journal_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_accounting_journal_rev1` (`accounting_journal_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_closed_year_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_closed_year_rev2_ledger_account_hk_fk` FOREIGN KEY (`ledger_account_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_ledger_account_rev1` (`ledger_account_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_general_journal_line_closed_year_rev2`
  ADD CONSTRAINT `nhl_general_journal_line_closed_year_rev2_operating_company_hk_fk` FOREIGN KEY (`operating_company_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_operating_company_rev1` (`operating_company_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_invoice_rev1`
  ADD CONSTRAINT `hub_invoice_rev1_pk` PRIMARY KEY (`invoice_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_invoice_header_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_invoice_header_fieldglass_us_rev1_pk` PRIMARY KEY (`invoice_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_invoice_header_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_invoice_header_fieldglass_us_rev1_invoice_hk_fk` FOREIGN KEY (`invoice_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_invoice_rev1` (`invoice_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4`
  ADD CONSTRAINT `nhl_invoice_line_rev4_pk` PRIMARY KEY (`invoice_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4`
  ADD CONSTRAINT `nhl_invoice_line_rev4_client_hk_fk` FOREIGN KEY (`client_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_client_rev1` (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4`
  ADD CONSTRAINT `nhl_invoice_line_rev4_invoice_hk_fk` FOREIGN KEY (`invoice_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_invoice_rev1` (`invoice_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4`
  ADD CONSTRAINT `nhl_invoice_line_rev4_supplier_hk_fk` FOREIGN KEY (`supplier_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_supplier_rev2` (`supplier_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4`
  ADD CONSTRAINT `nhl_invoice_line_rev4_worker_hk_fk` FOREIGN KEY (`worker_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_worker_rev1` (`worker_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_invoice_line_details_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_invoice_line_details_fieldglass_us_rev1_pk` PRIMARY KEY (`invoice_line_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_invoice_line_details_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_invoice_line_details_fieldglass_us_rev1_invoice_line_hk_fk` FOREIGN KEY (`invoice_line_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4` (`invoice_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_invoice_line_gie_rev1`
  ADD CONSTRAINT `csat_invoice_line_gie_rev1_pk` PRIMARY KEY (`invoice_line_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_invoice_line_gie_rev1`
  ADD CONSTRAINT `csat_invoice_line_gie_rev1_invoice_line_hk_fk` FOREIGN KEY (`invoice_line_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`nhl_invoice_line_rev4` (`invoice_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_job_request_rev1`
  ADD CONSTRAINT `hub_job_request_rev1_pk` PRIMARY KEY (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_commercials_striive_eu_rev1`
  ADD CONSTRAINT `sat_job_request_commercials_striive_eu_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_commercials_striive_eu_rev1`
  ADD CONSTRAINT `sat_job_request_commercials_striive_eu_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_job_request_custom_field_fieldglass_us_rev1`
  ADD CONSTRAINT `msat_job_request_custom_field_fieldglass_us_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_job_request_custom_field_fieldglass_us_rev1`
  ADD CONSTRAINT `msat_job_request_custom_field_fieldglass_us_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_job_request_custom_promoted_rev1`
  ADD CONSTRAINT `csat_job_request_custom_promoted_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_job_request_custom_promoted_rev1`
  ADD CONSTRAINT `csat_job_request_custom_promoted_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_striive_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_striive_eu_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_striive_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_striive_eu_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_bullhorn_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_bullhorn_eu_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_bullhorn_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_bullhorn_eu_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_job_request_details_fieldglass_us_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_fieldglass_us_rev1`
  ADD CONSTRAINT `sat_job_request_details_fieldglass_us_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_prounity_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_prounity_eu_rev1_pk` PRIMARY KEY (`job_request_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_job_request_details_prounity_eu_rev1`
  ADD CONSTRAINT `sat_job_request_details_prounity_eu_rev1_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2`
  ADD CONSTRAINT `nhl_journal_line_rev2_pk` PRIMARY KEY (`journal_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2`
  ADD CONSTRAINT `nhl_journal_line_rev2_accounting_journal_hk_fk` FOREIGN KEY (`accounting_journal_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_accounting_journal_rev1` (`accounting_journal_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2`
  ADD CONSTRAINT `nhl_journal_line_rev2_ledger_account_hk_fk` FOREIGN KEY (`ledger_account_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_ledger_account_rev1` (`ledger_account_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2`
  ADD CONSTRAINT `nhl_journal_line_rev2_operating_company_hk_fk` FOREIGN KEY (`operating_company_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_operating_company_rev1` (`operating_company_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2`
  ADD CONSTRAINT `nhl_journal_line_rev2_pay_period_hk_fk` FOREIGN KEY (`pay_period_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_pay_period_rev1` (`pay_period_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_journal_line_external_code_ukg_us_rev1`
  ADD CONSTRAINT `msat_journal_line_external_code_ukg_us_rev1_pk` PRIMARY KEY (`journal_line_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_journal_line_external_code_ukg_us_rev1`
  ADD CONSTRAINT `msat_journal_line_external_code_ukg_us_rev1_journal_line_hk_fk` FOREIGN KEY (`journal_line_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2` (`journal_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_journal_line_worktag_ukg_us_rev1`
  ADD CONSTRAINT `msat_journal_line_worktag_ukg_us_rev1_pk` PRIMARY KEY (`journal_line_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_journal_line_worktag_ukg_us_rev1`
  ADD CONSTRAINT `msat_journal_line_worktag_ukg_us_rev1_journal_line_hk_fk` FOREIGN KEY (`journal_line_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`nhl_journal_line_rev2` (`journal_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_ledger_account_rev1`
  ADD CONSTRAINT `hub_ledger_account_rev1_pk` PRIMARY KEY (`ledger_account_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1`
  ADD CONSTRAINT `hub_legal_entity_rev1_pk` PRIMARY KEY (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_legal_entity_consolidation_rev2`
  ADD CONSTRAINT `lnk_legal_entity_consolidation_rev2_pk` PRIMARY KEY (`legal_entity_consolidation_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_legal_entity_consolidation_rev2`
  ADD CONSTRAINT `lnk_legal_entity_consolidation_rev2_consolidation_group_hk_fk` FOREIGN KEY (`consolidation_group_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_consolidation_group_rev1` (`consolidation_group_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`lnk_legal_entity_consolidation_rev2`
  ADD CONSTRAINT `lnk_legal_entity_consolidation_rev2_legal_entity_hk_fk` FOREIGN KEY (`legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_legal_entity_consolidation_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_legal_entity_consolidation_effectivity_workday_rev1_pk` PRIMARY KEY (`legal_entity_consolidation_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_legal_entity_consolidation_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_legal_entity_consolidation_effectivity_workday_rev1_legal_entity_consolidation_hk_fk` FOREIGN KEY (`legal_entity_consolidation_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`lnk_legal_entity_consolidation_rev2` (`legal_entity_consolidation_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_legal_entity_details_client_portal_rev1`
  ADD CONSTRAINT `sat_legal_entity_details_client_portal_rev1_pk` PRIMARY KEY (`legal_entity_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_legal_entity_details_client_portal_rev1`
  ADD CONSTRAINT `sat_legal_entity_details_client_portal_rev1_legal_entity_hk_fk` FOREIGN KEY (`legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_legal_entity_profile_hubspot_rev1`
  ADD CONSTRAINT `sat_legal_entity_profile_hubspot_rev1_pk` PRIMARY KEY (`legal_entity_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_legal_entity_profile_hubspot_rev1`
  ADD CONSTRAINT `sat_legal_entity_profile_hubspot_rev1_legal_entity_hk_fk` FOREIGN KEY (`legal_entity_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_legal_entity_rev1` (`legal_entity_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_operating_company_rev1`
  ADD CONSTRAINT `hub_operating_company_rev1_pk` PRIMARY KEY (`operating_company_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_pay_period_rev1`
  ADD CONSTRAINT `hub_pay_period_rev1_pk` PRIMARY KEY (`pay_period_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_payroll_detail_rev2`
  ADD CONSTRAINT `nhl_payroll_detail_rev2_pk` PRIMARY KEY (`payroll_detail_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_payroll_detail_rev2`
  ADD CONSTRAINT `nhl_payroll_detail_rev2_operating_company_hk_fk` FOREIGN KEY (`operating_company_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_operating_company_rev1` (`operating_company_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_payroll_detail_rev2`
  ADD CONSTRAINT `nhl_payroll_detail_rev2_pay_period_hk_fk` FOREIGN KEY (`pay_period_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_pay_period_rev1` (`pay_period_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_payroll_detail_rev2`
  ADD CONSTRAINT `nhl_payroll_detail_rev2_worker_hk_fk` FOREIGN KEY (`worker_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_worker_rev1` (`worker_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_payroll_line_classification_rev1`
  ADD CONSTRAINT `csat_payroll_line_classification_rev1_pk` PRIMARY KEY (`payroll_detail_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${business_vault_schema}`.`csat_payroll_line_classification_rev1`
  ADD CONSTRAINT `csat_payroll_line_classification_rev1_payroll_detail_hk_fk` FOREIGN KEY (`payroll_detail_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`nhl_payroll_detail_rev2` (`payroll_detail_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_supplier_rev2`
  ADD CONSTRAINT `hub_supplier_rev2_pk` PRIMARY KEY (`supplier_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_supplier_details_gp_vendor_rev1`
  ADD CONSTRAINT `sat_supplier_details_gp_vendor_rev1_pk` PRIMARY KEY (`supplier_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`sat_supplier_details_gp_vendor_rev1`
  ADD CONSTRAINT `sat_supplier_details_gp_vendor_rev1_supplier_hk_fk` FOREIGN KEY (`supplier_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_supplier_rev2` (`supplier_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_timesheet_line_rev2`
  ADD CONSTRAINT `nhl_timesheet_line_rev2_pk` PRIMARY KEY (`timesheet_line_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_timesheet_line_rev2`
  ADD CONSTRAINT `nhl_timesheet_line_rev2_client_hk_fk` FOREIGN KEY (`client_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_client_rev1` (`client_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_timesheet_line_rev2`
  ADD CONSTRAINT `nhl_timesheet_line_rev2_job_request_hk_fk` FOREIGN KEY (`job_request_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_job_request_rev1` (`job_request_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`nhl_timesheet_line_rev2`
  ADD CONSTRAINT `nhl_timesheet_line_rev2_worker_hk_fk` FOREIGN KEY (`worker_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_worker_rev1` (`worker_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_wd_reference_rev1`
  ADD CONSTRAINT `hub_wd_reference_rev1_pk` PRIMARY KEY (`wd_reference_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_wd_reference_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_wd_reference_effectivity_workday_rev1_pk` PRIMARY KEY (`wd_reference_hk`, `load_dts`, `sub_seq`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`esat_wd_reference_effectivity_workday_rev1`
  ADD CONSTRAINT `esat_wd_reference_effectivity_workday_rev1_wd_reference_hk_fk` FOREIGN KEY (`wd_reference_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_wd_reference_rev1` (`wd_reference_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`hub_worker_rev1`
  ADD CONSTRAINT `hub_worker_rev1_pk` PRIMARY KEY (`worker_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_worker_skills_striive_eu_rev1`
  ADD CONSTRAINT `msat_worker_skills_striive_eu_rev1_pk` PRIMARY KEY (`worker_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_worker_skills_striive_eu_rev1`
  ADD CONSTRAINT `msat_worker_skills_striive_eu_rev1_worker_hk_fk` FOREIGN KEY (`worker_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_worker_rev1` (`worker_hk`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_worker_skills_hr_eu_rev1`
  ADD CONSTRAINT `msat_worker_skills_hr_eu_rev1_pk` PRIMARY KEY (`worker_hk`, `load_dts`, `sub_seq`, `mas_key`) NOT ENFORCED;

ALTER TABLE `${catalog}`.`${vault_schema}`.`msat_worker_skills_hr_eu_rev1`
  ADD CONSTRAINT `msat_worker_skills_hr_eu_rev1_worker_hk_fk` FOREIGN KEY (`worker_hk`)
  REFERENCES `${catalog}`.`${vault_schema}`.`hub_worker_rev1` (`worker_hk`) NOT ENFORCED;
