-- GENERATED by tools/emit_workday_landing.py. Do not edit.
-- Interim landing for Workday reference values; see the emitter for why this
-- is neither Bronze nor a stg_ table in raw_vault.

CREATE SCHEMA IF NOT EXISTS `${catalog}`.`workday_landing`;

CREATE TABLE IF NOT EXISTS `${catalog}`.`workday_landing`.`wd_reference_snapshot` (
  `reference_id_type` STRING NOT NULL,
  `reference_id` STRING NOT NULL,
  `descriptor` STRING,
  `snapshot_dts` TIMESTAMP NOT NULL
) USING DELTA;

CREATE TABLE IF NOT EXISTS `${catalog}`.`workday_landing`.`wd_reference_effectivity` (
  `reference_id_type` STRING NOT NULL,
  `reference_id` STRING NOT NULL,
  `reference_status` STRING NOT NULL,
  `effective_from` TIMESTAMP NOT NULL
) USING DELTA;
