#!/usr/bin/env python3
"""The gold layer's schemas, as DDL rendered from gold_layout.SCHEMAS.

SEPARATE FROM control_objects_gold.sql ON PURPOSE. That file's contract is the control
surface, and checks/control_conformance_check.py gates it against
control_standard.LAYER_TABLES["gold"]. Folding four unrelated CREATE SCHEMA statements
into it would widen a gate whose whole value is its narrowness.

CREATE SCHEMA IF NOT EXISTS, NEVER A REPLACE. DEF-61, measured 27 September 2026:
replacing a securable discards every grant held against it, and a schema is a securable.
This file is applied repeatedly by design, so it must be idempotent in the strict sense
-- running it twice must change nothing at all.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from accelerator import gold_layout  # noqa: E402

OUT_PATH = ROOT / "governance" / "gold_schemas.sql"


def render() -> str:
    lines = [
        "-- GENERATED by tools/emit_gold_schemas.py from accelerator.gold_layout.SCHEMAS.",
        "-- Do not edit. Run the emitter and commit the result.",
        "--",
        "-- Applied by checks/apply_gold_schemas.py, from the gold_build job.",
        "-- CREATE ... IF NOT EXISTS only: a schema is a securable, and replacing one",
        "-- discards every grant held against it (DEF-61).",
        "",
    ]
    for name, purpose in gold_layout.SCHEMAS.items():
        lines.append(f"-- {name}: {purpose}")
        lines.append(
            f"CREATE SCHEMA IF NOT EXISTS `${{gold_catalog}}`.`{name}`;")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
