#!/usr/bin/env python3
"""Emit the vault's PRIMARY KEY and FOREIGN KEY constraints as Unity Catalog DDL.

THE MODEL HAS ALWAYS KNOWN THESE AND THE LAKE HAS NEVER BEEN TOLD. 56 primary keys and 31
foreign keys are derived from `entity.parents` and published four ways -- the data
contracts, the DBML diagram, the OWL ontology and the source-to-target mapping -- and
measured 5 September 2026, `ADD CONSTRAINT` appeared ZERO times in this repository. So the
relationship model existed in every artefact a human reads and in none that a query
planner, a BI tool or an agent can see.

INFORMATIONAL, NOT ENFORCED, and that is not a compromise -- it is the only thing that
could work here. Unity Catalog does not enforce these, and enforcement would be wrong for
an insert-only vault: a satellite legitimately arrives before its hub within a run, and a
link row can precede the hub row it points at until the same update completes. What a
declared constraint buys is that the join path is discoverable rather than guessed, which
is the whole complaint the Genie Ontology paper makes about a schema that declares none.

THE TWO AUTHORITIES ARE REUSED, NEVER RE-DERIVED. `contract.grain` decides the primary key
-- it mirrors append_only_check's uniqueness rule deliberately, so a constraint here cannot
claim a grain the gate does not police -- and `contract.foreign_keys` decides the edges,
which is the same function the DBML and the ontology read. A third derivation of either
would be the duplicate-authority trap this repo has been bitten by four times.

NOT APPLIED BY ANY JOB, DELIBERATELY, and this file follows
`governance/control_objects_gold.sql` exactly: generated, committed, gated against drift,
and never run. Two things are unverified and only a workspace can settle them -- whether a
Spark Declarative Pipelines streaming table accepts `ALTER TABLE ... ADD CONSTRAINT` at
all, and whether every key column is already NOT NULL, which Unity Catalog requires of a
primary key. Emitting DDL nobody has run is honest; wiring it into the job before either
question is answered would be a task that fails on every load.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))

# THE STUB, for the same reason emit_data_contract installs one: accelerator.factory
# imports pyspark at module level, and this tool must run standalone on a machine that
# has none -- which is every offline CI job. sys.modules.setdefault so a stub already
# installed by a caller always wins over this one.
import emit_data_contract as _edc_stub  # noqa: E402,F401  (imported for its pyspark stub)

from accelerator import contract, factory, naming, spec  # noqa: E402

OUT_PATH = ROOT / "governance" / "vault_constraints.sql"

HEADER = """\
-- GENERATED by tools/emit_uc_constraints.py -- do not hand-edit.
-- verify_repo.py fails the build if this file and the model disagree.
--
-- The vault's relationship model, as Unity Catalog informational constraints. Derived from
-- metadata/entities/ through contract.grain (primary keys, mirroring append_only_check's
-- uniqueness rule) and contract.foreign_keys (edges, the same function the DBML diagram and
-- the OWL ontology read).
--
-- INFORMATIONAL, NEVER ENFORCED. Unity Catalog does not enforce these and enforcement would
-- be wrong here: a satellite legitimately arrives before its hub within a run. What they buy
-- is a join path a query planner, a BI tool or an agent can discover instead of guess.
--
-- NOTHING RUNS THIS YET. Two questions need a workspace, not an opinion:
--   1. does an SDP streaming table accept ALTER TABLE ... ADD CONSTRAINT?
--   2. is every key column already NOT NULL, which UC requires of a primary key?
-- Until both are answered this file is generated, committed and gated -- the same state
-- governance/control_objects_gold.sql has been in since 29 August.
--
-- ${catalog} and ${vault_schema} / ${business_vault_schema} are substituted by the caller.
"""


def _schema_var(entity) -> str:
    """Which schema variable this entity's table lives under.

    Business kinds land in the business vault, everything else in the raw vault. Read from
    naming.BUSINESS_KINDS rather than restated, because a second list of which kinds are
    business kinds is how a grant once named a table that does not exist in that schema.
    """
    return ("${business_vault_schema}" if entity.kind in naming.BUSINESS_KINDS
            else "${vault_schema}")


def constraint_statements(model) -> list[str]:
    """Every PK and FK statement, in a stable order.

    ONE STATEMENT PER REAL TABLE, not per entity. A raw satellite fans out to one table per
    source -- sat_job_request_details_bullhorn_eu -- so an entity-level statement would name
    a table that does not exist. entity.tables() is the same iterator factory.build emits
    from, so this cannot drift from what was actually created.
    """
    out: list[str] = []
    for entity in sorted(model.entities, key=lambda e: e.name):
        schema = _schema_var(entity)
        for src, table in entity.tables():
            qualified = f"`${{catalog}}`.`{schema}`.`{table}`"
            columns = [n for n, _k, _v in factory._projection(entity, src or entity.sources[0])]

            pk_cols = contract.grain(entity, columns)
            if pk_cols:
                cols = ", ".join(f"`{c}`" for c in pk_cols)
                out.append(
                    f"ALTER TABLE {qualified}\n"
                    f"  ADD CONSTRAINT `{table}_pk` PRIMARY KEY ({cols}) NOT ENFORCED;"
                )

            # The FK target is the PARENT's own table and the parent's own hash key. For a
            # roled leg -- a hierarchical link's parent_/child_ columns -- the referencing
            # column carries the role and the referenced one does not, which is what
            # contract.foreign_keys already returns.
            for column, ref in sorted(contract.foreign_keys(entity, model).items()):
                parent_table, parent_column = ref.rsplit(".", 1)
                parent = next((e for e in model.entities
                               if e.base_table == parent_table), None)
                if parent is None:
                    continue
                # THE CONSTRAINT MUST NAME THE PHYSICAL TABLE, not the stable view.
                # contract.foreign_keys() returns the unversioned name on purpose -- it
                # is what a CONSUMER joins to, and the data contract and the diagrams are
                # right to use it. A constraint is not a consumer: Unity Catalog cannot
                # declare a FOREIGN KEY against a view, and after the migration the
                # unversioned name IS a view. So this one site resolves the parent to its
                # physical name and every other consumer of foreign_keys() does not.
                parent_physical = parent.tables()[0][1]
                parent_q = f"`${{catalog}}`.`{_schema_var(parent)}`.`{parent_physical}`"
                out.append(
                    f"ALTER TABLE {qualified}\n"
                    f"  ADD CONSTRAINT `{table}_{column}_fk` FOREIGN KEY (`{column}`)\n"
                    f"  REFERENCES {parent_q} (`{parent_column}`) NOT ENFORCED;"
                )
    return out


def render(model) -> str:
    statements = constraint_statements(model)
    pk = sum(1 for s in statements if "PRIMARY KEY" in s)
    fk = len(statements) - pk
    body = "\n\n".join(statements)
    return (f"{HEADER}--\n-- {pk} primary key(s), {fk} foreign key(s), "
            f"{len(statements)} statement(s).\n\n{body}\n")


def main() -> int:
    model = spec.load_model(ROOT / "metadata" / "entities")
    OUT_PATH.write_text(render(model), encoding="utf-8")
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
