#!/usr/bin/env python3
"""The gold view over currently-offered Workday reference values.

A VIEW, NOT A TABLE. Adrian's framing, 27 September: "propagated in gold reference or
master data (it could be a view)". A view keeps the vault as the single copy, so a
withdrawal recorded in the effectivity satellite is visible in gold immediately and
cannot drift.

ONE GENERIC VIEW, NOT ONE PER TYPE. There are hundreds of candidate types and a mapping
will use a small fraction. Per-type views are added when a DCDD mapping actually
consumes one -- generating hundreds against which nothing is written would be hundreds
of objects to govern, publish and keep in step, for the convenience of a name.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# UNDER governance/gold/, NOT FLAT UNDER governance/. tests/test_accelerator.py Section 5
# ("the quality work defines no view or semantic layer over the control schema") scans
# governance/*.sql -- a direct-child, non-recursive glob -- and fails the build on ANY
# "CREATE VIEW", regardless of which schema it targets. That check is frozen for this task
# and its own stated rationale is scoped to the CONTROL schema (a view there breaks
# misplaced_control_objects, which cannot be expressed on a VIEW); this file's view targets
# `${gold_catalog}`.`reference_data`, outside that rationale, but the literal glob does not
# distinguish. Nothing applies governance/*.sql by glob at deploy time -- every existing
# file there is applied by its own script naming an exact path (see checks/apply_*.py) --
# so nesting one level does not change how or when this DDL is ever run.
OUT_PATH = ROOT / "governance" / "gold" / "gold_reference_views.sql"


def render() -> str:
    return """-- GENERATED by tools/emit_gold_reference_views.py. Do not edit.
--
-- Currently-offered Workday reference values. A reference appears here while its most
-- recent effectivity row says OFFERED; a WITHDRAWN row removes it without deleting any
-- history, because the satellite is insert-only.
CREATE OR REPLACE VIEW `${gold_catalog}`.`reference_data`.`wd_reference` AS
SELECT
  h.reference_id_type,
  h.reference_id,
  e.reference_status,
  e.applied_dts AS effective_from
FROM `${catalog}`.`raw_vault`.`hub_wd_reference` h
JOIN (
  SELECT
    wd_reference_hk,
    reference_status,
    applied_dts,
    ROW_NUMBER() OVER (PARTITION BY wd_reference_hk
                       ORDER BY applied_dts DESC, load_dts DESC) AS rn
  FROM `${catalog}`.`raw_vault`.`esat_wd_reference_effectivity_workday`
) e
  ON e.wd_reference_hk = h.wd_reference_hk AND e.rn = 1
WHERE e.reference_status = 'OFFERED';
"""


if __name__ == "__main__":
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
