#!/usr/bin/env python3
"""Generate resources/vault_pipeline.yml from the model's declared domains.

WHY GENERATED. Until 25 September 2026 one `raw_vault` pipeline declared the whole model:
34 entities, 38 streaming tables, 54 append flows and nine definition-time schema analyses
in a single graph. Two consequences, both measured that day on usnc_tds:

  * A SpecError in ONE entity killed all 38 tables. It happened four times in an afternoon --
    an untyped mask, a case-only alias collision, a NOT NULL derived column, a missing
    table -- and each time the other 37 went down with it.
  * The driver spent 30+ minutes in INITIALIZING at 50-57% GC and was lost twice
    ("Communication lost with driver"). All of it before a single row was read, so the cost
    is graph construction, not data.

The model is expected to reach ~100 entities.

src/pipelines/silver_vault.py has always been able to filter by domain -- `if DOMAINS:
model.entities = [e for e in model.entities if e.domain in DOMAINS]` -- and every entity
already declares one. The filter had never been used, because `var.domains` defaults to ""
and one pipeline therefore declared everything. This turns the existing filter into the
topology.

WHY FROM THE MODEL RATHER THAN BY HAND. Six near-identical pipeline blocks are six copies,
and the copy nobody is looking at is the one that goes stale -- a failure this repo has paid
for more than once. Adding a domain to an entity YAML regenerates the topology, so the
pipeline set cannot disagree with the model it is derived from. Byte-gated by verify_repo,
exactly as the other generated artefacts are.

MULTIPLE PIPELINES, ONE SCHEMA, and that is supported: Unity Catalog allows several
pipelines to publish into one catalog.schema provided no table is declared twice. Domains
PARTITION the entities, so no table is.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from accelerator import naming, spec  # noqa: E402

OUT = ROOT / "resources" / "vault_pipeline.yml"

HEADER = '''# The vault pipelines. Serverless, triggered, no full refresh.
#
# GENERATED by tools/emit_pipeline_resources.py from the domains the model declares.
# Do not edit by hand: verify_repo compares this file byte for byte against a fresh
# generation, so a hand edit is reported as drift rather than silently kept.
#
# ONE RAW PIPELINE PER DOMAIN, plus the Business Vault. The Raw Vault loads from Bronze and
# the Business Vault computes FROM the Raw Vault; an SDP pipeline targets ONE schema, so the
# two layers cannot share a pipeline even though they share one entry point
# (silver_vault.py). hfig.vault_layer tells that entry point which kinds to declare, and
# hfig.domains tells it which slice of the model.
#
# The raw pipelines all publish into the SAME schema, which Unity Catalog permits as long as
# no table is declared twice -- domains partition the entities, so none is. The benefit is
# that a definition-time failure in one domain no longer takes the other five down with it.
#
# NOTE ON full_refresh: it is set false in resources/vault_job.yml AND asserted by
# checks/append_only_check.py after every run. One full refresh rebuilds insert-only
# history from whatever happens to be in staging today -- silent, total, unrecoverable.
# Configuration, not culture.
resources:
  pipelines:
'''

FOOTER = '''
    # There were five throwaway `probe_*` pipelines here, carrying a comment saying
    # task 7 had removed them. Task 7 had not: they were still declared and would
    # still have deployed, into the schema this project no longer uses. Task 8
    # deleted them along with `probes/`. Their findings are in section 1 of
    # docs/superpowers/specs/2026-08-24-subproject3a-gp-journals-design.md, including
    # the probe objects still sitting in the workspace, which a bundle cannot remove.

    # There is no bronze_ingest pipeline. Bronze ingestion is out of scope (spec
    # decision D4): the estate's own raw-to-clean pipeline already lands
    # <source>_raw, and there is a schema per source system rather than one
    # bronze schema this bundle could name. src/pipelines/bronze_ingest.py is
    # still on disk and is removed by the source-rebind sub-project.
'''


def raw_domains(model) -> list[str]:
    """Every domain with at least one RAW entity, in a stable order.

    Sorted so the generated file's diff is readable, and derived from the entities rather
    than listed so a new domain arrives with its entity instead of after it.
    """
    return sorted({e.domain for e in model.entities
                   if e.kind not in naming.BUSINESS_KINDS and e.domain})


def pipeline_block(key: str, title: str, schema_var: str, layer: str,
                   domains: str, event_log: str, note: str = "") -> str:
    """One pipeline resource. Every block comes from here, so they cannot drift apart."""
    return f'''    {key}:
      name: "[${{bundle.target}}] hfig {title}"
      catalog: ${{var.catalog}}
      schema: ${{var.{schema_var}}}
      serverless: true
      continuous: false          # triggered: manifest-gated batch, compute stops after
      photon: true
      development: false
      channel: CURRENT
      configuration:
        hfig.expectations_table: ${{var.expectations_table}}
{note}        hfig.domains: {domains}
        # D5: which declared bindings emit an append flow HERE. Empty means all of them.
        # The table inventory does not depend on this -- every declared binding still
        # gets its streaming table -- only the flows do.
        hfig.active_sources: ${{var.active_sources}}
        hfig.region: ${{bundle.target}}
        # DEF-15: an SDP pipeline library cannot locate itself. __file__ is unbound, and
        # the code object's filename is a transient ipykernel path, not the workspace
        # path -- so src/ and metadata/ must be given to the entry point, not derived.
        hfig.source_root: ${{workspace.file_path}}
        # DEF-21: a MASK clause's function must be CATALOG-qualified. Inside the
        # pipeline a two-part `governance.mask_money` resolves against
        # spark_catalog, not the pipeline's catalog, and fails with SCHEMA_NOT_FOUND.
        hfig.catalog: ${{var.catalog}}
        hfig.vault_layer: {layer}
      libraries:
        - file:
            path: ../src/pipelines/silver_vault.py
      event_log:
        catalog: ${{var.catalog}}
        schema: ${{var.governance_schema}}
        name: {event_log}
'''


def render(model) -> str:
    domains = raw_domains(model)
    counts = {d: sum(1 for e in model.entities
                     if e.domain == d and e.kind not in naming.BUSINESS_KINDS)
              for d in domains}
    blocks = []
    for d in domains:
        note = (f"        # {counts[d]} raw entit{'y' if counts[d] == 1 else 'ies'}. "
                f"The domain is written in rather than taken from ${{var.domains}}:\n"
                f"        # the split IS the topology, so it cannot be varied per target\n"
                f"        # without changing which pipeline owns which table.\n")
        blocks.append(pipeline_block(
            key=f"raw_vault_{d}",
            title=f"raw vault -- {d}",
            schema_var="vault_schema",
            layer="raw",
            domains=d,
            event_log=f"pipeline_event_log_{d}",
            note=note,
        ))
    blocks.append(pipeline_block(
        key="business_vault",
        title="business vault",
        schema_var="business_vault_schema",
        layer="business",
        domains="${var.domains}",
        event_log="pipeline_event_log_bv",
    ))
    return HEADER + "\n".join(blocks) + FOOTER


def main() -> int:
    model = spec.load_model(ROOT / "metadata" / "entities")
    text = render(model)
    OUT.write_text(text, encoding="utf-8")
    doms = raw_domains(model)
    print(f"wrote {OUT.relative_to(ROOT)} -- {len(doms)} raw pipeline(s) "
          f"({', '.join(doms)}) plus business_vault")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
