#!/usr/bin/env python3
"""The INTERIM landing schema for Workday reference values.

INTERIM, AND BUILT TO BE DELETED. Bronze has no workday schema yet (measured 27
September: 01_usnc_bronze_dev has no schema matching workday or wd_). When it does, the
two bindings in metadata/entities/ move to 01_usnc_bronze_dev.workday_raw.* and this
schema is dropped -- one change, because nothing else references it.

NOT raw_vault, AND NOT stg_. stg_ means the SDP pipeline's append log for a staged
entity; DEF-42 rests on a staged kind having exactly two real tables. Landing here would
leave assert_append_only, assert_no_broad_grant and publish_stable_views asserting over
objects that are not entities -- gates quietly checking the wrong thing, which is worse
than gates failing.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "governance" / "workday_landing.sql"

SCHEMA = "workday_landing"
TABLES = {
    "wd_reference_snapshot": [
        ("reference_id_type", "STRING NOT NULL"),
        ("reference_id", "STRING NOT NULL"),
        ("descriptor", "STRING"),
        ("snapshot_dts", "TIMESTAMP NOT NULL"),
    ],
    "wd_reference_effectivity": [
        ("reference_id_type", "STRING NOT NULL"),
        ("reference_id", "STRING NOT NULL"),
        ("reference_status", "STRING NOT NULL"),
        ("effective_from", "TIMESTAMP NOT NULL"),
    ],
}


def render() -> str:
    lines = [
        "-- GENERATED by tools/emit_workday_landing.py. Do not edit.",
        "-- Interim landing for Workday reference values; see the emitter for why this",
        "-- is neither Bronze nor a stg_ table in raw_vault.",
        "",
        f"CREATE SCHEMA IF NOT EXISTS `${{catalog}}`.`{SCHEMA}`;",
        "",
    ]
    for table, cols in TABLES.items():
        body = ",\n".join(f"  `{n}` {t}" for n, t in cols)
        lines.append(
            f"CREATE TABLE IF NOT EXISTS `${{catalog}}`.`{SCHEMA}`.`{table}` (\n"
            f"{body}\n) USING DELTA;")
        lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    OUT_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {OUT_PATH.relative_to(ROOT)}")
