"""
HARD GATE: hash parity. Spark's output must equal the reference implementation.

This is the spike's Q3 hash-parity criterion, automated. It answers one question with
a number rather than an opinion: does this workspace, in this region, on this runtime,
produce exactly the digests the rulebook says it should?

Run it:
  * once per region before the first load;
  * after any Databricks runtime or channel change;
  * in CI on every change to src/accelerator/hashing.py.

It fails on ANY divergence. A single mismatched digest means keys computed in this
region cannot be joined to keys computed elsewhere, and the registry can never
reconcile them -- which is unrecoverable without re-keying the estate.

The same golden vectors are also the artefact to reconcile against the EDM
record_hash convention. If the workbook's convention produces different digests for
these inputs, the difference must be resolved in the rulebook, not bridged by a
translation layer.
"""

from __future__ import annotations

# DEF-12: serverless `spark_python_task` exec()s this file and does NOT define
# __file__, so every Path(__file__) below raised NameError and the gate died before
# asserting anything. compile() still records the real path in the code object.
if "__file__" not in globals():  # noqa: F821
    import inspect as _inspect

    __file__ = _inspect.currentframe().f_code.co_filename

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pyspark.sql import SparkSession, functions as F  # noqa: E402

from accelerator import hashing as h, sql_text  # noqa: E402

VECTORS = Path(__file__).resolve().parents[1] / "tests" / "golden_hash_vectors.json"


def _literal(value: object) -> str:
    """Render a Python value as a SQL literal, preserving the NULL/blank distinction.

    THE ESCAPE IS NOT THIS FILE'S TO CHOOSE, and choosing it here was a silent hole in
    GATE ZERO. This function doubled the apostrophe -- the ANSI escape, which Spark does
    not read as an escape at all: `SELECT 'O''Brien'` PARSES and returns `OBrien`,
    measured in Spark 3.5.9. Spark would then have hashed OBrien while reference_key()
    hashed O'Brien, and the first vector carrying an apostrophe would have failed this
    gate as a HASH mismatch -- sending whoever debugged it into the rulebook, which was
    correct, rather than into this line, which was not. accelerator.sql_text is the one
    escaper, so the gate that proves Spark agrees with Python cannot be the thing that
    makes them disagree.
    """
    if value is None:
        return "CAST(NULL AS STRING)"
    return sql_text.literal(str(value))


def check_rulebook_match(vectors: dict) -> list[str]:
    """The vectors must have been generated by the rulebook currently in the repo."""
    declared = vectors["rulebook"]
    actual = {
        "version": h.RULEBOOK_VERSION,
        "algorithm": h.ALGORITHM,
        "delimiter": h.DELIMITER,
        "null_token": h.NULL_TOKEN,
        "key_uppercase": h.KEY_UPPERCASE,
        "trim": h.TRIM,
        "binary_output": h.BINARY_OUTPUT,
        "hashdiff_uppercase": h.HASHDIFF_UPPERCASE,
    }
    if declared != actual:
        return [
            "golden vectors were generated under a different rulebook -- regenerate "
            f"them deliberately.\n      vectors={declared}\n      repo   ={actual}"
        ]
    return []


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--region", default="unknown", help="for the report only")
    args = ap.parse_args()

    vectors = json.loads(VECTORS.read_text(encoding="utf-8"))
    problems = check_rulebook_match(vectors)
    if problems:
        for p in problems:
            print(f"  * {p}")
        return 1

    spark = SparkSession.builder.getOrCreate()
    print(f"hash parity :: region={args.region} rulebook={h.RULEBOOK_VERSION} "
          f"algorithm={h.ALGORITHM}\n")

    # ------------------------------------------------------------------ keys
    print("business keys")
    for case in vectors["keys"]:
        values = case["values"]
        cols = [f"{_literal(v)} AS c{i}" for i, v in enumerate(values)]
        expr = h.hash_key([f"c{i}" for i in range(len(values))],
                          source_scope=case["source_scope"])
        # compare on hex so the assertion is readable in logs
        hex_expr = expr.replace("UNHEX(", "LOWER(").replace(", 256))", ", 256))") \
            if h.BINARY_OUTPUT else expr
        row = spark.sql(
            f"SELECT LOWER(HEX({expr})) AS got, {h.DELIMITER!r} AS d FROM (SELECT {', '.join(cols)})"
        ).collect()[0]
        got = row["got"]
        want = case["sha256_hex"]
        ok = got == want
        print(f"  {'PASS' if ok else 'FAIL'}  {case['name']:28s} {want[:16]}...")
        if not ok:
            problems.append(
                f"key {case['name']}: pre-hash string {case['pre_hash_string']!r}\n"
                f"        expected {want}\n        got      {got}"
            )

    # -------------------------------------------------------------- hashdiffs
    print("\nhashdiffs")
    baseline = None
    for case in vectors["hashdiffs"]:
        values = case["values"]
        cols = [f"{_literal(v)} AS c{i}" for i, v in enumerate(values)]
        expr = h.hashdiff([f"c{i}" for i in range(len(values))])
        row = spark.sql(
            f"SELECT LOWER(HEX({expr})) AS got FROM (SELECT {', '.join(cols)})"
        ).collect()[0]
        got, want = row["got"], case["sha256_hex"]
        ok = got == want
        print(f"  {'PASS' if ok else 'FAIL'}  {case['name']:28s} {want[:16]}...")
        if not ok:
            problems.append(
                f"hashdiff {case['name']}: pre-hash string {case['pre_hash_string']!r}\n"
                f"        expected {want}\n        got      {got}"
            )
        if case["name"] == "baseline":
            baseline = got

    # ------------------------------------------------- the schema-evolution property
    # Asserted directly in Spark, because it is the property that decides whether
    # adding a column to a satellite reinserts every row in the estate.
    if baseline is not None:
        appended = next(c for c in vectors["hashdiffs"] if c["name"] == "appended_null_column")
        values = appended["values"]
        cols = [f"{_literal(v)} AS c{i}" for i, v in enumerate(values)]
        expr = h.hashdiff([f"c{i}" for i in range(len(values))])
        got = spark.sql(
            f"SELECT LOWER(HEX({expr})) AS got FROM (SELECT {', '.join(cols)})"
        ).collect()[0]["got"]
        if got == baseline:
            print("\n  PASS  appending a null column does NOT change the hashdiff")
        else:
            problems.append(
                "appending a null column CHANGED the hashdiff in Spark. Adding a "
                "column to any satellite will reinsert every row. Check that "
                "REGEXP_REPLACE tail-stripping behaves as the reference expects."
            )

    print("\n" + "=" * 66)
    if problems:
        print(f"HASH PARITY GATE FAILED -- {len(problems)} divergence(s):")
        for p in problems:
            print(f"  * {p}")
        return 1
    print(f"HASH PARITY GATE PASSED: {len(vectors['keys'])} keys and "
          f"{len(vectors['hashdiffs'])} hashdiffs match the reference exactly")
    return 0


if __name__ == "__main__":
    # DEF-14: serverless spark_python_task runs this under an ipykernel wrapper that
    # surfaces SystemExit as an exception and marks the task FAILED -- for exit code 0
    # as readily as for 1. A PASSING gate therefore failed its task and blocked every
    # task behind it. Exit explicitly only on failure; falling off the end is exit 0.
    # Identical behaviour for a shell, correct behaviour on serverless.
    _rc = main()
    if _rc:
        sys.exit(_rc)
